(function(){
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  const scoreFor=(streak)=>100+streak*25, remaining=(start,elapsed)=>Math.max(0,start-elapsed);
  function collectIfHit(s){if(Math.hypot(s.x-s.roll.x,s.y-s.roll.y)>=9)return s;return {...s,saved:s.saved+1,streak:s.streak+1,score:s.score+scoreFor(s.streak+1),roll:spot(),bandit:spot()};}
  if(typeof module!=="undefined"){module.exports={clamp,scoreFor,remaining,collectIfHit};return;}
  const field=document.querySelector('#playfield'),player=document.querySelector('#player'),roll=document.querySelector('#roll'),scoreEl=document.querySelector('#score'),savedEl=document.querySelector('#saved'),timeEl=document.querySelector('#time'),status=document.querySelector('#status');
  let state={x:50,y:50,score:0,saved:0,time:30,streak:0,running:false,last:0,started:0,raf:0,roll:{x:20,y:25},bandit:{x:75,y:70}}; const speed=230;
  function spot(){return{x:10+Math.random()*80,y:18+Math.random()*68};}
  function place(el,x,y){el.style.left=`${x}%`;el.style.top=`${y}%`;el.style.transform='translate(-50%,-50%)';}
  function render(){place(player,state.x,state.y);place(roll,state.roll.x,state.roll.y);scoreEl.textContent=state.score;savedEl.textContent=state.saved;timeEl.textContent=Math.ceil(state.time);}
  function reset(){cancelAnimationFrame(state.raf);window.keys={};state={x:50,y:50,score:0,saved:0,time:30,streak:0,running:false,last:0,started:0,raf:0,roll:spot(),bandit:spot()};document.querySelector('.bandit')?.remove();const b=document.createElement('div');b.className='bandit';b.textContent='🛍️';field.append(b);state.banditEl=b;status.textContent='Press start. The shelves are already empty.';render();}
  function hit(){const next=collectIfHit(state);if(next!==state){state=next;status.textContent=state.streak>2?`HOT STREAK x${state.streak}! The hoard grows.`:'One roll secured. Guard it with your life.';}}
  function frame(t){if(!state.running)return;const dt=Math.min((t-state.last)/1000,.05);state.last=t;state.time=30-(t-state.started)/1000;if(state.time<=0){state.time=0;state.running=false;status.textContent=`PANIC OVER. ${state.saved} roll${state.saved===1?'':'s'} saved, ${state.score} points.`;render();return}const k=window.keys||{};let dx=(k.ArrowRight||k.d?1:0)-(k.ArrowLeft||k.a?1:0),dy=(k.ArrowDown||k.s?1:0)-(k.ArrowUp||k.w?1:0),len=Math.hypot(dx,dy)||1;state.x=clamp(state.x+dx/len*speed*dt/field.clientWidth*100,5,95);state.y=clamp(state.y+dy/len*speed*dt/field.clientHeight*100,12,92);state.bandit.x+=Math.sin(t/700)*dt*3;state.bandit.y+=Math.cos(t/900)*dt*2;state.bandit.x=clamp(state.bandit.x,8,92);state.bandit.y=clamp(state.bandit.y,18,88);place(state.banditEl,state.bandit.x,state.bandit.y);if(Math.hypot(state.x-state.bandit.x,state.y-state.bandit.y)<9){state.score=Math.max(0,state.score-50);state.streak=0;status.textContent='A tote-bag bandit bumped you. -50 points!';state.bandit=spot();}hit();render();state.raf=requestAnimationFrame(frame)}
  window.keys={};window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();window.keys[e.key]=true}});window.addEventListener('keyup',e=>window.keys[e.key]=false);window.addEventListener('blur',()=>window.keys={});
  field.addEventListener('pointermove',e=>{if(!state.running)return;const r=field.getBoundingClientRect();state.x=clamp((e.clientX-r.left)/r.width*100,5,95);state.y=clamp((e.clientY-r.top)/r.height*100,12,92);});
  document.querySelector('#start').onclick=()=>{if(!state.running){if(state.time<=0)reset();state.running=true;state.last=performance.now();state.started=state.last;status.textContent='GO! Dodge the tote-bag bandit.';field.focus();state.raf=requestAnimationFrame(frame);}};document.querySelector('#restart').onclick=reset;reset();window.LastRoll={clamp};if(typeof module!=='undefined')module.exports={clamp,scoreFor,remaining,collectIfHit};
})();
